import type { Category } from '../types';

/**
 * The shipped starter content: twenty artworks across two categories.
 *
 * The images sit in `public/artwork/` and are referenced by URL, so their
 * palettes are extracted at play time by the ordinary pipeline with no special
 * case for being built in -- the same path a loaded pack takes.
 *
 * Boards are left to `specFor`, which walks the lattice and shape lists by
 * position so twenty subjects come out visibly different from each other, and
 * ramps difficulty across each category.
 *
 * `hue` is the one thing set here rather than derived, and it is not a taste
 * decision: most of these images have a dominant hue between 43 and 87 degrees,
 * because lit dust and starlight are warm. Left alone almost every board would
 * be the same amber. The values below were computed by `assignDistinctHues` in
 * `src/content/hues.ts`, which spaces a category's boards evenly around the
 * wheel and gives each artwork the slot closest to a colour it actually
 * contains.
 *
 * Assigned **per category**, not once across everything. Twenty-seven subjects
 * on one wheel sit 13 degrees apart, which is not a difference anyone can see;
 * per category they are 33, 40 and 51 degrees apart, better than the 18 the
 * single pass gave. The trade is that a hue can recur between categories --
 * never within a list you are looking at, which is the only place it would
 * read as a repeat.
 *
 * They are recorded rather than recomputed at load time because working them
 * out means clustering every image in the category, and nobody should wait for
 * that to open a menu. A pack loaded from a zip runs the same function during
 * ingest, where the palettes are already in hand.
 *
 * The split into two categories is about the facts, not the pictures. Half
 * these images are astronomical objects and can carry astronomy; the rest are
 * human-scale scenes -- figures under strange skies, machines, ruins -- where a
 * fact about spiral arms would be pasted on. Those get a category about scale,
 * deep time and what we are made of, which is what they are actually about.
 */

export const SAMPLER_CATEGORIES: Category[] = [
  {
    id: 'cosmos',
    title: 'The Cosmos',
    blurb: 'Deep space, and the physics that shapes it.',
    mosaic: { kind: 'url', url: './artwork/plates/cosmos.jpg' },
    subjects: [
      {
        id: 'spiral-galaxy',
        title: 'Spiral Galaxy',
        blurb: 'A hundred billion suns, held in a turning disc.',
        hue: 267,
        artwork: { kind: 'url', url: './artwork/spiral-galaxy.jpg' },
        facts: [
          'A spiral galaxy’s arms look blue and its centre gold for the same reason: the arms are where new stars are still forming, and the hottest, bluest of those burn out fastest, while the core is left holding older, cooler, redder ones.',
          'Spiral arms are not solid structures that wind up over time. They are density waves — stars drift into them and out again, the way a traffic jam persists on a motorway while individual cars pass through it.',
          'The Milky Way is a barred spiral roughly 100,000 light years across. Every picture you have seen of it from the outside is an illustration, because nothing has ever been far enough away to take that photograph.',
          'Galaxies are mostly empty space. When Andromeda meets the Milky Way in about four billion years, the two will pass through each other with almost no stars colliding.',
          'Counts of how many galaxies fill the observable universe have ranged from a few hundred billion to two trillion, depending on how many of the faintest ones a survey can pick out.',
        ],
      },
      {
        id: 'andromeda',
        title: 'Andromeda',
        blurb: 'The nearest big galaxy, and the furthest thing you can see unaided.',
        hue: 333,
        artwork: { kind: 'url', url: './artwork/andromeda.jpg' },
        facts: [
          'Andromeda is about 2.5 million light years away, and is the most distant object most people can see with the naked eye. The light reaching you tonight left before our species existed.',
          'Until the 1920s it was called the Andromeda Nebula and assumed to be a cloud inside our own galaxy. Edwin Hubble found variable stars in it, measured the distance, and moved it outside.',
          'It is coming towards us at about 110 km per second. In roughly four billion years the two galaxies will merge.',
          'It spans about six times the width of the full Moon in our sky. We only ever notice the bright core, because everything outside it is too faint for the eye to pick up.',
          'It may hold around a trillion stars, several times the Milky Way’s count, while being no more massive overall — a difference in how the mass is divided up rather than how much there is.',
        ],
      },
      {
        id: 'pinwheel-galaxy',
        title: 'Pinwheel Galaxy',
        blurb: 'Two clean arms, which is rarer than it looks.',
        hue: 300,
        artwork: { kind: 'url', url: './artwork/pinwheel-galaxy.jpg' },
        facts: [
          'A “grand design” spiral has two clear arms running unbroken around the disc. Only about one spiral in ten is this tidy; the rest are flocculent — patchy and many-armed.',
          'The pink knots strung along the arms are clouds of hydrogen lit from inside by newborn stars. They mark where the galaxy is still building.',
          'Clean arms are often somebody else’s doing. A close pass by a neighbouring galaxy can pull a ragged disc into a symmetrical spiral.',
          'Blue light in the arms comes from stars a few million years old. The yellow core is stars billions of years old. You are looking at two very different ages in one picture.',
          'The disc is astonishingly thin. The Milky Way is about 100,000 light years across and only around 1,000 thick — proportionally thinner than a sheet of paper is wide.',
        ],
      },
      {
        id: 'barred-spiral',
        title: 'Barred Spiral',
        blurb: 'A straight span of stars across the core, with the arms trailing from its ends.',
        hue: 202,
        artwork: { kind: 'url', url: './artwork/barred-spiral.jpg' },
        facts: [
          'Roughly two thirds of spiral galaxies have a bar — a straight structure through the centre, with the spiral arms starting at its tips rather than at the core.',
          'The bar works as a funnel. It channels gas inward, feeding bursts of star formation and sometimes the black hole at the centre.',
          'The Milky Way has one, and we only established that in the 1990s. Mapping a structure you are sitting inside is genuinely hard.',
          'Bars are not permanent. They form, strengthen and can dissolve again over billions of years, so a galaxy may be barred for only part of its life.',
          'A bar is a resonance, not an object: the stars in it are on elongated orbits that happen to line up, and individual stars pass through and out again.',
        ],
      },
      {
        id: 'galaxy-cluster',
        title: 'Galaxy Cluster',
        blurb: 'The largest things gravity has managed to hold together.',
        hue: 136,
        artwork: { kind: 'url', url: './artwork/galaxy-cluster.jpg' },
        facts: [
          'A rich cluster can hold a thousand galaxies bound together by gravity. They are the largest structures in the universe that are held together at all — everything bigger is still expanding apart.',
          'Most of a cluster’s ordinary matter is not in the galaxies. It is thin gas between them, heated to tens of millions of degrees and glowing in X-rays.',
          'Clusters bend the light of whatever lies behind them, magnifying distant galaxies into arcs. The same effect weighs the cluster, because the bending depends on its mass.',
          'Those weighings are a large part of how we know most of the mass in the universe is something we cannot see directly.',
          'Cluster galaxies harass each other. Close passes and the pressure of that hot gas strip a galaxy of its own, which shuts down its star formation and leaves it red.',
        ],
      },
      {
        id: 'saturn',
        title: 'Saturn',
        blurb: 'The solar system’s great ringed world.',
        hue: 104,
        artwork: { kind: 'url', url: './artwork/saturn.jpg' },
        facts: [
          'Saturn’s rings are almost entirely water ice, in pieces ranging from specks of dust to chunks the size of a house.',
          'The rings span about 280,000 km but are only tens of metres thick through most of that. Scaled to the width of a football pitch, they would be thinner than a sheet of paper.',
          'They may be young. Measurements from the Cassini mission suggest the rings formed perhaps 10 to 100 million years ago — long after the first dinosaurs.',
          'Saturn is less dense than water. Given an ocean big enough to hold it, the planet would float.',
          'All four giant planets have rings. Saturn’s are simply the only ones bright enough to pick out through a small telescope.',
        ],
      },
      {
        id: 'gas-giant-clouds',
        title: 'Cloud Tops',
        blurb: 'A world with weather and no ground.',
        hue: 71,
        artwork: { kind: 'url', url: './artwork/gas-giant-clouds.jpg' },
        facts: [
          'A gas giant has no surface. Descending, the atmosphere simply thickens until it behaves as a liquid, and there is no line anywhere to call the ground.',
          'Jupiter’s bands are jet streams, and neighbouring bands run in opposite directions. The curls between them are where those opposing winds shear against each other.',
          'Hydrogen and helium are colourless, so none of the colour comes from the bulk of the planet. It comes from traces — ammonia ice, ammonium hydrosulfide, and compounds still not firmly identified.',
          'The Great Red Spot is a storm wider than Earth that has been watched continuously for around 190 years. It has been shrinking for most of the time we have measured it.',
          'The fastest winds in the solar system, roughly 2,000 km/h, blow on Neptune — the planet that receives the least sunlight of any of them.',
        ],
      },
      {
        id: 'crab-nebula',
        title: 'The Crab Nebula',
        blurb: 'Wreckage from an explosion people watched in 1054.',
        hue: 235,
        artwork: { kind: 'url', url: './artwork/crab-nebula.jpg' },
        facts: [
          'The Crab is the debris of a star seen to explode in 1054. Chinese astronomers recorded a “guest star” bright enough to be visible in daylight for over three weeks.',
          'At its centre is a pulsar: a neutron star spinning about 30 times a second, sweeping a beam past us like a lighthouse.',
          'That neutron star is roughly 20 km across and heavier than the Sun. A teaspoon of its material would weigh about as much as a mountain.',
          'The nebula is still flying apart at around 1,500 km per second, and it is measurably larger in photographs taken decades apart.',
          'Much of its glow is not from hot gas but from electrons spiralling through a magnetic field at nearly the speed of light.',
        ],
      },
      {
        id: 'supernova-remnant',
        title: 'Supernova Remnant',
        blurb: 'What a star leaves behind when it dies.',
        hue: 38,
        artwork: { kind: 'url', url: './artwork/supernova-remnant.jpg' },
        facts: [
          'A supernova can briefly outshine its entire galaxy: one dying star out-glowing a hundred billion others.',
          'The expanding shell is not moving into emptiness. It slams into the gas already there and lights it up, which is why remnants look like tangled filaments rather than clean bubbles.',
          'Elements heavier than iron cannot be made by ordinary fusion. They need the energy of an explosion like this one.',
          'The shock front can trigger the collapse of nearby gas clouds, so one star’s death starts the next generation’s birth.',
          'A remnant stays visible for tens of thousands of years before it thins out and merges with the interstellar medium.',
        ],
      },
      {
        id: 'accretion-disc',
        title: 'Accretion Disc',
        blurb: 'Matter falling in, and glowing on the way down.',
        hue: 169,
        artwork: { kind: 'url', url: './artwork/accretion-disc.jpg' },
        facts: [
          'Material falling towards a compact object almost never falls straight in. It arrives with sideways motion, so it settles into a disc and spirals inward instead.',
          'Friction within the disc heats it to millions of degrees. That is why accretion discs shine, often outshining everything else in the neighbourhood.',
          'Accretion is the most efficient energy source known. Falling into a spinning black hole can release tens of per cent of a mass as energy; hydrogen fusion manages under one per cent.',
          'The same physics builds planets. A young star’s disc is far cooler, so instead of blazing, its dust sticks together.',
          'Quasars are accretion discs around supermassive black holes, and are among the brightest sustained objects in the universe.',
        ],
      },
      {
        id: 'black-hole',
        title: 'Black Hole',
        blurb: 'A boundary in spacetime, not an object.',
        hue: 5,
        artwork: { kind: 'url', url: './artwork/black-hole.jpg' },
        facts: [
          'The glow in an image of a black hole is not the hole. It is the accretion disk: matter torn apart and heated to millions of degrees as it spirals inward.',
          'The event horizon is a boundary, not a surface. Falling through a large one there is no wall and no jolt — nothing nearby marks the moment you can no longer return.',
          'The first direct image of a black hole’s shadow was published in 2019, showing the giant at the centre of the galaxy M87.',
          'Supermassive black holes sit at the centre of most large galaxies, including ours. The Milky Way’s is about four million times the Sun’s mass.',
          'They are not permanent. Hawking radiation means a black hole slowly evaporates, though a stellar-mass one would take vastly longer than the current age of the universe.',
        ],
      },
    ],
  },
  {
    id: 'our-place',
    title: 'Our Place In It',
    blurb: 'Standing under it, made of it, and trying to reach it.',
    mosaic: { kind: 'url', url: './artwork/plates/our-place.jpg' },
    subjects: [
      {
        id: 'meadow-galaxy',
        title: 'Night Over a Meadow',
        blurb: 'The view most people have lost.',
        hue: 320,
        artwork: { kind: 'url', url: './artwork/meadow-galaxy.jpg' },
        facts: [
          'About a third of humanity can no longer see the Milky Way from where they live, and roughly 80% of people in North America cannot.',
          'Your eyes need 20 to 30 minutes to fully dark-adapt, and a single glance at a white light resets most of it.',
          'Look slightly to the side of a faint star and it brightens. The edge of the retina is more sensitive to dim light than the centre, so astronomers deliberately look away from what they want to see.',
          'Under a genuinely dark sky perhaps 3,000 stars are visible at once. From a city centre it can be a few dozen.',
          'Nearly every star you can see unaided lies within about 1,000 light years — a small bubble inside a galaxy 100,000 light years across.',
        ],
      },
      {
        id: 'mountain-night',
        title: 'Peaks Under Starlight',
        blurb: 'Why observatories are built where the air runs out.',
        hue: 40,
        artwork: { kind: 'url', url: './artwork/mountain-night.jpg' },
        facts: [
          'Great telescopes sit on mountains to get above as much of the atmosphere as possible — above its water vapour, and above much of its turbulence.',
          'Stars twinkle because of air, not because of anything the star is doing. Adaptive optics cancels it by flexing a mirror hundreds of times a second to undo the distortion as it happens.',
          'The silicon and oxygen in the rock beneath you and the calcium in your bones were made by the same process, inside stars that died long before the Sun.',
          'Mountains on Earth have a height limit set by gravity: pile rock higher and the base begins to flow. Olympus Mons on Mars is around two and a half times the height of Everest, because Mars pulls less hard.',
          'The darkest skies left on Earth are mostly at altitude or at sea, and a growing number of them are formally protected as dark-sky reserves.',
        ],
      },
      {
        id: 'cloud-sea',
        title: 'Above the Clouds',
        blurb: 'How thin the air actually is.',
        hue: 80,
        artwork: { kind: 'url', url: './artwork/cloud-sea.jpg' },
        facts: [
          'In photographs of Earth from orbit the atmosphere is a thin bright line. Most of its mass sits within about 16 km of the ground — thinner, proportionally, than the skin on an apple.',
          'Space is usually reckoned to begin at the Kármán line, 100 km up, where the air is so thin you would need to fly faster than orbital speed for wings to hold you.',
          'Clouds are not water vapour. Vapour is an invisible gas; a cloud is liquid droplets or ice crystals that have condensed out of it.',
          'A moderate cumulus cloud can carry hundreds of tonnes of water and still float, because the air it displaces weighs more than it does.',
          'The blue of the sky is sunlight scattered by air molecules, which deflect short wavelengths far more strongly than long ones. With no air, the daytime sky is black.',
        ],
      },
      {
        id: 'the-ascent',
        title: 'The Ascent',
        blurb: 'Leaving is a problem of speed, not height.',
        hue: 120,
        artwork: { kind: 'url', url: './artwork/the-ascent.jpg' },
        facts: [
          'Reaching orbit is about going sideways fast enough — roughly 28,000 km/h — not about going up. Straight up and you simply come back down.',
          'Most of a rocket on the pad is fuel. Around 85 to 90% of its mass is propellant, and only a few per cent is payload.',
          'That is the rocket equation biting: every extra kilogram of fuel needs more fuel to lift it, so the cost of a bit more speed rises steeply.',
          'Orbit is falling. A spacecraft in free fall around Earth is accelerating downward the whole time; it simply moves sideways fast enough to keep missing.',
          'Coming back is the harder half. Re-entry has to shed all that speed as heat, which is why heat shields, not engines, are the critical part.',
        ],
      },
      {
        id: 'alien-sky',
        title: 'Another World’s Sky',
        blurb: 'Daylight elsewhere probably looks nothing like ours.',
        hue: 280,
        artwork: { kind: 'url', url: './artwork/alien-sky.jpg' },
        facts: [
          'More than five thousand planets around other stars have been confirmed, and most were found without ever being seen — detected by the tiny dip in a star’s light as a planet crosses in front of it.',
          'Sky colour depends on the air. Mars has a butterscotch day sky and a blue sunset, the reverse of Earth’s, because its dust scatters light the opposite way round.',
          'Many stars come in pairs or more, so a double sunset is an ordinary sight in the galaxy rather than an exotic one.',
          'Red dwarfs are by far the most common kind of star, so the most common daylight in the universe is probably dim and red.',
          'A planet orbiting close to a small star tends to become tidally locked, keeping one face towards it permanently: endless day on one side, endless night on the other.',
        ],
      },
      {
        id: 'young-sun',
        title: 'A Sun Being Born',
        blurb: 'Where planets come from.',
        hue: 160,
        artwork: { kind: 'url', url: './artwork/young-sun.jpg' },
        facts: [
          'Stars form inside cold clouds of gas and dust that collapse under their own gravity until the centre is hot and dense enough for fusion to start.',
          'The leftover material forms a disc, and planets condense out of it. That is why the planets of our solar system all orbit in nearly the same plane and the same direction.',
          'A Sun-like star takes around ten million years to settle into stable hydrogen burning, and then stays there for roughly ten billion.',
          'A newborn star blows a fierce wind that clears out the nursery around it, which is part of why young clusters of stars drift apart rather than staying together.',
          'The Sun is roughly a third brighter now than when Earth formed, and will keep brightening. Life has spent four billion years under a slowly rising light.',
        ],
      },
      {
        id: 'star-stuff',
        title: 'Star Stuff',
        blurb: 'You are made of the ash.',
        hue: 240,
        artwork: { kind: 'url', url: './artwork/star-stuff.jpg' },
        facts: [
          'Every element heavier than helium was assembled inside a star, or in the collision of two dead ones. There is no other significant source.',
          'The calcium in your bones and the iron in your blood were made in stars that finished burning before the Sun existed.',
          'The hydrogen in you is older still. It was made in the first few minutes after the Big Bang and has never been made in quantity since.',
          'Gold and platinum need something more violent than an ordinary star. Much of it appears to come from neutron stars colliding.',
          'By mass a human body is around 65% oxygen and 18% carbon. Both are stellar ash, which makes most of you, quite literally, the remains of stars.',
        ],
      },
      {
        id: 'the-machine',
        title: 'The Machine',
        blurb: 'Almost everything we know, something else went and looked at.',
        hue: 0,
        artwork: { kind: 'url', url: './artwork/the-machine.jpg' },
        facts: [
          'Nearly everything known about other worlds was sent back by robots. No human being has yet travelled further than the Moon.',
          'Voyager 1, launched in 1977, is the most distant human-made object. Its radio signal now takes around a day to make the round trip.',
          'Spacecraft computers are deliberately decades behind consumer hardware. Radiation-hardened chips are slow, and out there reliability beats speed every time.',
          'Mars rovers are not driven with a joystick. The round-trip light delay runs from about 8 to 40 minutes, so each day’s driving is sent up as a script and executed alone.',
          'Voyager carries a gold-plated record of sounds and images from Earth, aimed at nobody in particular, on the chance that something eventually finds it.',
        ],
      },
      {
        id: 'the-ruins',
        title: 'What We Leave',
        blurb: 'The orbits are getting crowded.',
        hue: 200,
        artwork: { kind: 'url', url: './artwork/the-ruins.jpg' },
        facts: [
          'Tens of thousands of debris objects larger than 10 cm are tracked in orbit around Earth, and there are many millions too small to track but still fast enough to destroy a satellite.',
          'A collision in orbit makes debris that causes further collisions. Run far enough, that cascade — Kessler syndrome — could make some orbits unusable for generations.',
          'Altitude decides how long junk lasts. Below about 600 km the thin remaining air drags things down within decades; above 1,000 km, objects can stay up for centuries.',
          'Debris hits at closing speeds around 10 km per second, where a fleck of paint carries the energy of a bullet.',
          'The footprints left on the Moon have no wind or water to erase them. Barring an unlucky impact, they will still be there in a million years.',
        ],
      },
    ],
  },
  {
    id: 'patterns',
    title: 'Patterns in Nature',
    blurb: 'Spirals, ripples, and colour made from structure rather than pigment.',
    mosaic: { kind: 'url', url: './artwork/plates/patterns.jpg' },
    subjects: [
      {
        id: 'seedling',
        title: 'Seedling',
        blurb: 'Built almost entirely out of air.',
        hue: 261,
        artwork: { kind: 'url', url: './artwork/seedling.jpg' },
        facts: [
          'Leaves are green because chlorophyll absorbs red and blue light strongly and reflects the green. The colour you see is the part the plant is throwing away.',
          'Nearly every carbon atom in a plant came out of the air as carbon dioxide. A tree is mostly built from a gas.',
          'Almost all the oxygen in the atmosphere was put there by photosynthesis. Before it began, the air had essentially none.',
          'Photosynthesis converts only a few per cent of the light that falls on a leaf, far less than a solar panel — but it has been running for over three billion years and it rebuilt the planet.',
          'Living things everywhere on Earth are made of the same handful of elements, and every one of them heavier than hydrogen was made inside a star.',
        ],
      },
      {
        id: 'the-drop',
        title: 'The Drop',
        blurb: 'Surface tension, caught in the act.',
        hue: 210,
        artwork: { kind: 'url', url: './artwork/the-drop.jpg' },
        facts: [
          'A drop is a drop because water molecules pull on one another. A sphere is the shape with the least surface for a given volume, so that is what the pulling produces.',
          'A drop landing on still water can rebound as a thin column and pinch off a second droplet on the way up. That is the moment the classic photograph catches.',
          'The rings spreading outwards are capillary waves, ruled by surface tension rather than gravity — so the shorter ones travel *faster*, the opposite of waves at sea.',
          'A water strider stands on the surface rather than in it. Its weight is simply less than the force holding the surface together.',
          'Water’s surface tension is unusually high for a liquid because its molecules hydrogen-bond to each other. The same bonding is why it stays liquid at temperatures where similar molecules are gases.',
        ],
      },
      {
        id: 'thin-film',
        title: 'Thin Film',
        blurb: 'Every colour here, and not a drop of pigment.',
        hue: 313,
        artwork: { kind: 'url', url: './artwork/thin-film.jpg' },
        facts: [
          'A soap bubble contains no pigment at all. Light reflects off both surfaces of a film a few hundred nanometres thick, and the two reflections interfere — reinforcing some wavelengths and cancelling others.',
          'Which colour appears depends on how thick the film is at that point. As it drains under gravity the bands drift downwards, which is why a bubble’s colours are always moving.',
          'Just before it pops, the top of a bubble turns black. The film there is thinner than a wavelength of light, and the two reflections cancel almost exactly.',
          'The rainbow on a wet road is the same effect in a film of oil, and so is the sheen on a beetle’s back.',
          'A bubble is the smallest surface that can enclose its air. It is the same rule that makes a falling drop spherical, working from the inside out.',
        ],
      },
      {
        id: 'phyllotaxis',
        title: 'Phyllotaxis',
        blurb: 'The angle a plant uses to avoid shading itself.',
        hue: 159,
        artwork: { kind: 'url', url: './artwork/phyllotaxis.jpg' },
        facts: [
          'New leaves emerge about 137.5 degrees around from the last — the golden angle. Nothing packs more evenly: any simpler fraction of a turn eventually lines new growth up with old and wastes the light.',
          'Count the spirals in a sunflower head or a pine cone and you get consecutive Fibonacci numbers, 34 and 55 or 55 and 89, because those fractions come closest to that angle.',
          'No plant is doing arithmetic. Each bud forms wherever there is most room, and the angle falls out of that one local rule.',
          'The same spirals turn up in unrelated species, because the pattern belongs to the process — anything added one piece at a time around a growing centre does it.',
          'Growth like this is self-similar: the arrangement looks the same whether the plant has ten leaves or a thousand.',
        ],
      },
      {
        id: 'structural-colour',
        title: 'Structural Colour',
        blurb: 'Grind it to powder and the colour disappears.',
        hue: 107,
        artwork: { kind: 'url', url: './artwork/structural-colour.jpg' },
        facts: [
          'An iridescent feather holds no green or blue pigment. Its colour comes from layers of keratin and melanin spaced to reinforce particular wavelengths of light.',
          'Grind such a feather to powder and the colour vanishes with the structure. Grind a pigmented feather and the powder keeps its colour.',
          'Because it depends on the angle you look from, structural colour shifts as the bird turns. Pigment looks the same from everywhere.',
          'Almost no bird makes blue pigment. Nearly every blue feather in the world is structural.',
          'Butterfly wings, beetle shells and a few berries use the same trick. It has evolved independently many times, which suggests it is an easy thing for biology to find.',
        ],
      },
      {
        id: 'ammonite',
        title: 'The Logarithmic Spiral',
        blurb: 'The only curve that keeps its shape as it grows.',
        hue: 4,
        artwork: { kind: 'url', url: './artwork/ammonite.jpg' },
        facts: [
          'A shell grows only at its opening, adding material without changing proportion. That produces a logarithmic spiral — the one curve that stays the same shape however large it gets.',
          'Ammonites swam the seas for more than 300 million years and died out alongside the dinosaurs, having already outlasted almost everything else.',
          'The chambers coiled inside were ballast. Flooding them or filling them with gas let the animal sink or rise, much as a submarine does.',
          'The shimmer on a fossil shell is nacre: microscopic plates of aragonite stacked about a wavelength of light apart. Structural colour again, from an animal that died before there were flowers.',
          'Nacre is also extraordinarily tough for something made of chalk. Its brick-and-mortar layering stops cracks from running.',
        ],
      },
      {
        id: 'refraction',
        title: 'Refraction',
        blurb: 'Light bending because it changed speed.',
        hue: 56,
        artwork: { kind: 'url', url: './artwork/refraction.jpg' },
        facts: [
          'Refraction is nothing more than light changing speed. It travels about a quarter slower through water than through air, and bends at the boundary as a result.',
          'A sphere of glass or water makes an image of whatever is behind it, upside down, because the bending brings rays to a focus.',
          'Past a certain angle, light cannot leave water at all and reflects back inside. That total internal reflection is what carries signals along a fibre-optic cable.',
          'Different colours bend by slightly different amounts, which is what splits white light in a prism.',
          'A rainbow is that splitting, inside raindrops. It is always centred on the point directly opposite the sun from where you stand, so no two people ever see quite the same one.',
        ],
      },
    ],
  },
  {
    id: 'small-company',
    title: 'Small Company',
    blurb: 'Six small lives, at the range where you can watch them working.',
    subjects: [
      {
        id: 'slime-mould',
        title: 'The Slime Mould',
        blurb: 'One cell, no brain, and a talent for shortest paths.',
        hue: 35,
        artwork: { kind: 'url', url: './artwork/slime-mould.jpg' },
        facts: [
          'Physarum polycephalum is a single cell containing many nuclei. It has no brain, no neurons and no nervous system of any kind, and it can grow to cover a square metre.',
          'Placed in a maze with food at both ends, it withdraws from the dead ends and leaves a single tube along the shortest route between them. The result was published in Nature in 2000.',
          'Given oat flakes laid out like the cities around Tokyo, it grew a network of tubes with much the same efficiency and fault tolerance as the actual rail system.',
          'It can be habituated: trained to cross a strip of harmless but unpleasant caffeine, it stops hesitating — and a trained one that fuses with an untrained one passes the habit on.',
          'It keeps time. Exposed to cold dry air at regular intervals it slows in anticipation of the next one, and slows again on schedule after the intervals stop.',
        ],
      },
      {
        id: 'caterpillar',
        title: 'The Caterpillar',
        blurb: 'An animal that dissolves most of itself and starts again.',
        hue: 155,
        artwork: { kind: 'url', url: './artwork/caterpillar.jpg' },
        facts: [
          'Inside the pupa most of the caterpillar breaks down into a soup. Small clusters of cells called imaginal discs survive it, and the adult is built from those.',
          'Moths trained as caterpillars to avoid a particular smell still avoided it after metamorphosis. Something of the memory survives the rebuild.',
          'A caterpillar has roughly 4,000 muscles. A human has about 630.',
          'A monarch caterpillar increases its mass around two thousand fold between hatching and pupating, almost all of it milkweed.',
          'The stubby legs along its middle are not legs. They are prolegs — fleshy, hooked, and abandoned entirely at metamorphosis.',
        ],
      },
      {
        id: 'garden-snail',
        title: 'The Snail',
        blurb: 'A tongue of teeth, and a foot that rides on its own glue.',
        hue: 335,
        artwork: { kind: 'url', url: './artwork/garden-snail.jpg' },
        facts: [
          'A snail feeds with a radula: a ribbon carrying thousands of microscopic teeth, rasped across the food and replaced from behind as it wears out.',
          'It moves on one muscular foot by sending waves of contraction along it, riding on mucus that behaves as a solid until it is sheared and then flows.',
          'That mucus lets a snail cross a razor blade unharmed, and climb glass, and hang upside down from it.',
          'Sealed behind a dried plug of its own mucus, a land snail can wait out months of drought without feeding.',
          'Snail and sea slug neurons are unusually large — large enough to record from one at a time — which is why much of what is known about how a single nerve cell learns was learned from them.',
        ],
      },
      {
        id: 'blue-morpho',
        title: 'The Blue Morpho',
        blurb: 'A blue with no blue in it.',
        hue: 215,
        artwork: { kind: 'url', url: './artwork/blue-morpho.jpg' },
        facts: [
          'There is no blue pigment anywhere in the wing. The scales carry ridges in stacked layers spaced to cancel most wavelengths and reinforce blue.',
          'The underside is drab brown with eyespots. In flight the animal alternates between brilliant and nearly invisible with every wingbeat.',
          'Because the colour is structural rather than chemical it does not fade. Museum specimens a century old are as blue as the day they were caught.',
          'Wet the wing with a liquid that fills the gaps between the ridges and the blue shifts or disappears, then returns as it dries.',
          'The flash can be picked out from several hundred metres away, which has made the wing a model for structural colour in paints and displays.',
        ],
      },
      {
        id: 'forest-floor',
        title: 'The Forest Floor',
        blurb: 'The most crowded place most people never look at.',
        hue: 95,
        artwork: { kind: 'url', url: './artwork/forest-floor.jpg' },
        facts: [
          'A single handful of forest soil contains more individual organisms than there are human beings alive.',
          'Woodlice are crustaceans, not insects. They are closer relatives of crabs than of beetles, and they breathe through structures that must stay damp.',
          'Their blood carries oxygen on copper rather than iron, so it is blue-green rather than red — and they eat their own droppings partly to recover the copper.',
          'Springtails launch themselves many times their own body length using a forked tail held under tension beneath the abdomen and released like a catch.',
          'Most of a forest’s living activity is underground. The visible trees are the smaller half of the arrangement.',
        ],
      },
      {
        id: 'poppy',
        title: 'The Poppy',
        blurb: 'A flower that waits decades for the ground to be broken.',
        hue: 275,
        artwork: { kind: 'url', url: './artwork/poppy.jpg' },
        facts: [
          'Poppy seed can lie dormant in soil for decades and germinate only when the ground is disturbed. That is why poppies covered the churned fields of the Western Front.',
          'The petals are folded and crumpled inside the bud like a packed parachute, and pull themselves flat within hours of opening.',
          'Red poppies offer no nectar at all. They trade in pollen alone, and are visited mostly by bees collecting it.',
          'To a bee the flower does not look red. Bees see ultraviolet, and the petals carry a pattern in it that no human eye has ever seen unaided.',
          'A single flower lasts a day or two. A single seed capsule can hold several thousand seeds.',
        ],
      },
    ],
  },
  {
    id: 'the-rare-hour',
    title: 'The Rare Hour',
    blurb: 'Things that only happen sometimes, and never for very long.',
    subjects: [
      {
        id: 'bioluminescence',
        title: 'The Burning Sea',
        blurb: 'Water that lights up where it is disturbed.',
        hue: 288,
        artwork: { kind: 'url', url: './artwork/bioluminescence.jpg' },
        facts: [
          'Certain single-celled dinoflagellates flash when the water around them is sheared, so a breaking wave lights along its own edge and a footprint glows for a moment.',
          'Each flash lasts about a tenth of a second, and the cell cannot immediately make another.',
          'The reaction is nearly cold. Almost all of the energy leaves as light rather than heat, which no lamp humans have built can match.',
          'One explanation is the burglar alarm: the flash makes whatever is grazing on them visible to whatever eats grazers.',
          'Bioluminescence has evolved independently dozens of separate times, and most of it happens in the deep sea — where making your own light is the ordinary condition, not the exception.',
        ],
      },
      {
        id: 'whale-fall',
        title: 'The Whale Fall',
        blurb: 'One death that feeds a world for fifty years.',
        hue: 144,
        artwork: { kind: 'url', url: './artwork/whale-fall.jpg' },
        facts: [
          'A large whale sinking to the seabed supports a succession of entirely different communities, one after another, for decades.',
          'Scavengers strip the flesh within months. Then bone-eating worms of the genus Osedax bore in with root-like structures and dissolve the bone with acid.',
          'Osedax has no mouth and no gut. It lives on symbiotic bacteria, and its males are microscopic and live inside the female.',
          'The bones hold enough fat to sustain a community running on sulphide rather than sunlight for years after the flesh is gone.',
          'More than a hundred species have been recorded on a single fall, and some of them have never been found anywhere else.',
        ],
      },
      {
        id: 'total-eclipse',
        title: 'Totality',
        blurb: 'A coincidence of apparent sizes, and a temporary one.',
        hue: 0,
        artwork: { kind: 'url', url: './artwork/total-eclipse.jpg' },
        facts: [
          'The Sun is about four hundred times the Moon’s width and about four hundred times further away, so the two appear almost exactly the same size from here.',
          'The coincidence is temporary. The Moon is receding about 3.8 cm a year, and in roughly 600 million years total eclipses will stop happening.',
          'Totality is the only time the corona can be seen with the naked eye: a million degrees, and about a millionth as bright as the disc it surrounds.',
          'Helium was identified in the Sun’s spectrum during the eclipse of 1868, decades before anyone found it on Earth.',
          'The shadow crosses the ground faster than sound. Totality at any one spot lasts at most about seven and a half minutes, and usually far less.',
        ],
      },
      {
        id: 'dark-adapted',
        title: 'The Dark-Adapted Eye',
        blurb: 'Half an hour to earn, one careless moment to lose.',
        hue: 216,
        artwork: { kind: 'url', url: './artwork/dark-adapted.jpg' },
        facts: [
          'Full dark adaptation takes twenty to thirty minutes to build, and a single glance at a white light undoes almost all of it.',
          'Night vision runs on rods, and there is only one kind of rod. A genuinely dark scene is therefore seen through a single channel: night has no colour.',
          'There are no rods at the very centre of the retina, which is why a faint star vanishes when you look straight at it and returns when you look slightly to one side.',
          'A dark-adapted rod can respond to a single photon — about the limit physics allows any detector to reach.',
          'Red light preserves adaptation because rods are least sensitive to long wavelengths. That is why observatories are lit in red.',
        ],
      },
      {
        id: 'vanishing-sky',
        title: 'The Vanishing Sky',
        blurb: 'The oldest view there is, and most people have never had it.',
        hue: 72,
        artwork: { kind: 'url', url: './artwork/vanishing-sky.jpg' },
        facts: [
          'More than eighty per cent of people — and over ninety-nine per cent of those in Europe and the United States — live under a sky that is never fully dark.',
          'The Milky Way itself is hidden from more than a third of humanity, including sixty per cent of Europeans and nearly eighty per cent of North Americans.',
          'Artificial sky brightness is rising by something like ten per cent a year in many places, considerably faster than the population under it.',
          'The Bortle scale runs from 1 to 9. Most city dwellers have never stood under anything better than an 8.',
          'Migrating birds, hatchling sea turtles and night-flying insects navigate by natural light, and are pulled off course by ours.',
        ],
      },
    ],
  },
  {
    id: 'the-elements',
    title: 'The Elements',
    blurb: 'Seven of the kinds of stuff there are. Everything else is arrangement.',
    subjects: [
      {
        id: 'quicksilver',
        title: 'Quicksilver',
        blurb: 'The only metal that runs, and the reason not to hold it.',
        hue: 0,
        artwork: { kind: 'url', url: './artwork/quicksilver.jpg' },
        facts: [
          'Mercury is the only metal that is liquid at room temperature. Its symbol, Hg, is from hydrargyrum: water-silver.',
          'It is so dense that iron floats on it. A litre weighs about thirteen and a half kilograms.',
          'Its surface tension is so high that it does not wet glass, and a spilled drop breaks into smaller beads that each behave exactly like the whole.',
          'Most of it is won from cinnabar, a red ore of mercury and sulphur that was also ground into the pigment vermilion.',
          'It is a slow poison that builds up in the body. Hatters who used mercury salts to felt fur developed tremors and confusion, which is where “mad as a hatter” comes from.',
        ],
      },
      {
        id: 'bromine',
        title: 'Bromine',
        blurb: 'A liquid that fumes, named for the smell, and missed by the man who had it in a bottle.',
        hue: 206,
        artwork: { kind: 'url', url: './artwork/bromine.jpg' },
        facts: [
          'Bromine is the only non-metal that is liquid at room temperature: dark red-brown, and fuming the moment the bottle is opened. The name is from the Greek for stench.',
          'It was identified in 1826 by Antoine Balard, aged twenty-three, in the brine left over from a salt marsh.',
          'Justus von Liebig already had a bottle of it. He had labelled it as a compound of iodine and chlorine and put it on a shelf, and only recognised what it was after Balard’s announcement.',
          'Seawater carries about sixty-five parts per million of bromide. The Dead Sea holds vastly more, and most bromine is still drawn from brines.',
          'Silver bromide was the light-sensitive salt in photographic film for over a century. Bromine compounds also went into leaded petrol, to carry the lead out through the exhaust, and into flame retardants.',
        ],
      },
      {
        id: 'iodine',
        title: 'The Violet Vapour',
        blurb: 'A solid that skips being a liquid, and a few milligrams a mind depends on.',
        hue: 309,
        artwork: { kind: 'url', url: './artwork/iodine.jpg' },
        facts: [
          'Warmed gently, solid iodine passes straight into a violet vapour without melting, and the vapour settles back into crystals on anything cold. The name is from the Greek for violet-coloured.',
          'It was discovered in 1811 by Bernard Courtois, in the ash of seaweed he was burning to make saltpetre for Napoleon’s gunpowder.',
          'Mendeleev placed iodine after tellurium although it is lighter, because its chemistry demanded it. He was right, and the reason, atomic number, was not found until 1913.',
          'The thyroid hormones that set the pace of the body carry iodine atoms. An adult holds about fifteen to twenty milligrams of iodine, most of it in the thyroid.',
          'Iodine deficiency is the leading preventable cause of intellectual disability in the world, which is why table salt has been iodised since the 1920s.',
        ],
      },
      {
        id: 'malachite',
        title: 'Malachite',
        blurb: 'Copper, banded and green, and nine thousand years of price.',
        hue: 154,
        artwork: { kind: 'url', url: './artwork/malachite.jpg' },
        facts: [
          'Malachite is copper carbonate. It grows in rounded, grape-like crusts, and cut through it shows the concentric bands of its growth.',
          'Copper was the first metal people worked. Beads hammered from native copper are around nine thousand years old, and the axe found with Ötzi the Iceman was cast copper.',
          'Ground malachite was the green eye paint of ancient Egypt, and a painter’s pigment for millennia after.',
          'Copper surfaces kill bacteria on contact within hours. Hospitals fit copper door handles and bed rails for that reason.',
          'The green skin of the Statue of Liberty is copper weathered to its own carbonates and sulphates: the same chemistry as malachite, grown over a century in the open air.',
        ],
      },
      {
        id: 'zinc-spangle',
        title: 'The Spangle',
        blurb: 'Zinc crystallising on steel: identical atoms, and no two flakes alike.',
        hue: 51,
        artwork: { kind: 'url', url: './artwork/zinc-spangle.jpg' },
        facts: [
          'The spangle on galvanised steel is zinc crystallising as the coating cools. Every atom of zinc is identical, and no two spangle crystals are the same shape.',
          'Zinc packs into a hexagonal lattice, the same symmetry as ice, and its crystals branch the way frost does.',
          'Zinc protects steel by corroding in its place. Even where the coating is scratched through, the zinc around the scratch gives itself up first.',
          'Brass is copper with zinc in it. Zinc was being smelted in India by the twelfth century, six hundred years before Europe isolated it.',
          'Hundreds of human enzymes need a zinc atom to work. The body holds about two grams and keeps no reserve, so a diet short of it shows quickly in growth and immunity.',
        ],
      },
      {
        id: 'star-regulus',
        title: 'The Star Regulus',
        blurb: 'The star in antimony that Newton chased for thirty years.',
        hue: 257,
        artwork: { kind: 'url', url: './artwork/star-regulus.jpg' },
        facts: [
          'Antimony is a brittle, silvery metalloid. Its symbol, Sb, comes from stibium, the Latin name of its sulphide ore, which was ground into the black eye paint kohl.',
          'Reduced from its ore and cooled slowly, a button of antimony crystallises with a star pattern across its surface: the star regulus. Regulus means little king.',
          'Isaac Newton prepared it again and again. He wrote about a million words on alchemy, never published, and the star regulus, which alchemists believed pointed the way to gold, runs through his notebooks.',
          'Antimony expands slightly as it solidifies, like water. Added to lead it made type metal fill every corner of a mould, which is how sharp printed letters were cast for five hundred years.',
          'In its day it was a medicine. Antimony pills were swallowed as a purgative, passed through unchanged, and recovered to be used again, sometimes for generations.',
        ],
      },
      {
        id: 'carbon',
        title: 'The Diamond and the Flower',
        blurb: 'The same atoms, twice, at two very different prices.',
        hue: 103,
        artwork: { kind: 'url', url: './artwork/carbon.jpg' },
        facts: [
          'A diamond and a flower are made of the same element. The diamond is nothing but carbon; the flower is carbon with water and a little else arranged around it.',
          'Most diamonds formed more than a billion years ago, over a hundred and fifty kilometres down, and were carried up in volcanic eruptions of a kind that no longer happen.',
          'Diamond is not carbon’s stable form. At the surface it is slowly becoming graphite, so slowly that nothing will notice for longer than the Earth has existed.',
          'The carbon in a flower was carbon dioxide in the air a few months earlier, pulled in through the leaves and built into petals.',
          'Carbon is made inside stars, three helium nuclei at a time, through a coincidence in nuclear energy levels so exact that it was predicted before it was measured.',
        ],
      },
    ],
  },
];
