/**
 * Builds src/content/story.ts from docs/story/chapter-one-breakdown.md.
 *
 * The breakdown document is the single source of truth for the Archivist's
 * tale: it is what gets read and edited. This turns it into typed data, matching
 * each entry to a shipped subject by position within its collection, and refuses
 * to build if the counts disagree -- a scene attached to the wrong picture is
 * worse than a missing one.
 *
 *   npx tsx tools/build-story.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { SAMPLER_CATEGORIES } from '../src/content/sampler';

const SOURCE = 'docs/story/chapter-one-breakdown.md';
const TARGET = 'src/content/story.ts';

const HEADINGS: Record<string, string> = {
  'THE COSMOS': 'cosmos',
  'OUR PLACE IN IT': 'our-place',
  'PATTERNS IN NATURE': 'patterns',
};

interface Entry {
  title: string;
  passage: string[];
}
interface Collection {
  categoryId: string;
  opening: string[];
  entries: Entry[];
  closing?: string[];
}

const lines = readFileSync(SOURCE, 'utf8').split('\n');

/** Consecutive '>' lines from `start` (after any blank lines), as paragraphs. */
function quote(start: number): { paragraphs: string[]; next: number } {
  let i = start;
  while (i < lines.length && lines[i]!.trim() === '') i++;
  const raw: string[] = [];
  while (i < lines.length && lines[i]!.startsWith('>')) {
    const line = lines[i]!;
    raw.push(line === '>' ? '' : line.replace(/^>\s?/, ''));
    i++;
  }
  // Blank quote lines separate paragraphs.
  const paragraphs = raw
    .join('\n')
    .split(/\n\s*\n/)
    .map((p) => p.replace(/\s*\n\s*/g, ' ').trim())
    .filter(Boolean);
  return { paragraphs, next: i };
}

const collections: Collection[] = [];
let current: Collection | null = null;
let entry: Entry | null = null;

for (let i = 0; i < lines.length; ) {
  const line = lines[i]!;
  const top = /^# (.+)$/.exec(line);
  if (top && HEADINGS[top[1]!.trim()]) {
    current = { categoryId: HEADINGS[top[1]!.trim()]!, opening: [], entries: [] };
    collections.push(current);
    i++;
    continue;
  }
  if (/^## What changed/.test(line)) break;
  if (!current) {
    i++;
    continue;
  }
  if (/^## Opening/.test(line)) {
    const q = quote(i + 1);
    current.opening = q.paragraphs;
    i = q.next;
    continue;
  }
  if (/^## Cliffhanger/.test(line)) {
    const q = quote(i + 1);
    // The closing "End of Chapter One." line is presentation, not story.
    current.closing = q.paragraphs.filter((p) => !/^\*End of Chapter/.test(p));
    i = q.next;
    continue;
  }
  const head = /^## \d+ · (.+?)(?: — NEW)?$/.exec(line);
  if (head) {
    entry = { title: head[1]!.trim(), passage: [] };
    current.entries.push(entry);
    i++;
    continue;
  }
  if (entry && /^\*\*Passage/.test(line)) {
    const q = quote(i + 1);
    entry.passage = q.paragraphs;
    i = q.next;
    continue;
  }
  i++;
}

// Validate against the shipped content before writing anything.
const problems: string[] = [];
for (const c of collections) {
  const category = SAMPLER_CATEGORIES.find((s) => s.id === c.categoryId);
  if (!category) {
    problems.push(`no shipped category '${c.categoryId}'`);
    continue;
  }
  if (c.entries.length !== category.subjects.length) {
    problems.push(`${c.categoryId}: ${c.entries.length} entries for ${category.subjects.length} subjects`);
  }
  if (c.opening.length === 0) problems.push(`${c.categoryId}: no opening`);
  // Titles are compared with apostrophes normalised: the document is typed by
  // hand and a straight quote is not a different picture.
  const plain = (s: string) => s.replace(/[’‘]/g, "'").trim();
  c.entries.forEach((e, j) => {
    const subject = category.subjects[j];
    if (!subject) return;
    if (plain(e.title) !== plain(subject.title)) {
      problems.push(`${c.categoryId}[${j}]: breakdown says '${e.title}', subject is '${subject.title}'`);
    }
    if (e.passage.length === 0) problems.push(`${c.categoryId}[${j}] ${e.title}: no passage`);
    // Every folio should deliver a scene, not a fragment: a stub here means a
    // passage that will read as an offcut when it lands on the reveal panel.
    const words = e.passage.join(' ').split(/\s+/).length;
    if (words < 90) problems.push(`${c.categoryId}[${j}] ${e.title}: passage is only ${words} words`);
  });
}
if (problems.length) {
  console.error('story does not match the shipped content:\n  ' + problems.join('\n  '));
  process.exit(1);
}

const q = (s: string) => JSON.stringify(s);
const arr = (items: string[], indent: string) =>
  items.length === 0 ? '[]' : `[\n${items.map((s) => `${indent}  ${q(s)},`).join('\n')}\n${indent}]`;

let out = `// GENERATED by tools/build-story.ts from ${SOURCE}.
// Edit the document, not this file; then run: npx tsx tools/build-story.ts
//
// The Archivist's tale, Chapter One. This is fiction, kept apart from the
// science facts each subject carries and shown in a different register.
import type { CollectionTale } from './types';

export const CHAPTER = { number: 1, title: 'The Still Things' } as const;

export const TALES: CollectionTale[] = [
`;
for (const c of collections) {
  const category = SAMPLER_CATEGORIES.find((s) => s.id === c.categoryId)!;
  out += `  {\n    categoryId: ${q(c.categoryId)},\n    opening: ${arr(c.opening, '    ')},\n    entries: [\n`;
  c.entries.forEach((e, j) => {
    out += `      {\n        subjectId: ${q(category.subjects[j]!.id)},\n        passage: ${arr(e.passage, '        ')},\n      },\n`;
  });
  out += `    ],\n`;
  if (c.closing) out += `    closing: ${arr(c.closing, '    ')},\n`;
  out += `  },\n`;
}
out += `];

export function taleFor(categoryId: string): CollectionTale | undefined {
  return TALES.find((t) => t.categoryId === categoryId);
}
`;
writeFileSync(TARGET, out);
const entries = collections.reduce((n, c) => n + c.entries.length, 0);
console.log(`wrote ${TARGET}: ${collections.length} collections, ${entries} entries`);
